 export const SCENE_KEYS = Object.freeze({
    LOGIN_SCENE: 'LOGIN_SCENE',
    PRELOAD_SCENE: 'PRELOAD_SCENE',
    TUTORIAL_SCENE: 'TUTORIAL_SCENE',
    GAME_SCENE: 'GAME_SCENE',
    HUD_SCENE: 'HUD_SCENE',
    SHOP_SCENE: 'SHOP_SCENE',
    ITEMBAG_SCENE: 'ITEMBAG_SCENE',
});